SET MODE MYSQL;
create schema if not exists `TESTDB`;

CREATE TABLE `USER` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(20) NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  UNIQUE INDEX `USER_NAME_UNIQUE` (`USER_NAME` ASC) ,
  PRIMARY KEY (`USER_ID`))  ENGINE = InnoDB;


CREATE TABLE `SUMMARY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `GROUP_NAME` VARCHAR(20) NOT NULL,
  `COMMENTS` VARCHAR(255) NULL,
  `IS_SHOW` VARCHAR(1) NULL,
  PRIMARY KEY (`ID`)) ENGINE = InnoDB;

CREATE TABLE `USER_GROUP` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(20) NOT NULL,
  `GROUP_NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`)) ENGINE = InnoDB;



