eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

server:
    port: 8881


spring:
    application:
        name: config-client
    cloud:
        config:
            label: master
            profile: dev
            uri: http://127.0.0.1:8888/
            discovery:
                service-id: config-server
                enabled: true

