create SCHMEA`CODE_ROAD` DEFAULT CHARACTER SET utf8;


create TABLE `CODE_ROAD`.`TRANS` (
  `GUID` CHAR(36) NOT NULL,
  `TRANS_ID` VARCHAR(15) NULL,
  `TRANS_AMOUNT` DECIMAL(25) NULL,
  `TRANS_DATE` TIMESTAMP(6) NULL,
  `CREATED_AT` TIMESTAMP(6) NULL,
  `CREATED_BY` VARCHAR(15) NULL,
  `UPDATED_AT` TIMESTAMP(6) NULL,
  `UPDATED_BY` VARCHAR(15) NULL,
  PRIMARY KEY (`GUID`));

create TABLE `CODE_ROAD`.`EXT` (
  `GUID` CHAR(36) NOT NULL,
  `EXT_ID` VARCHAR(15) NULL,
  `EXT_AMOUNT` DECIMAL(25) NULL,
  `EXT_DATE` TIMESTAMP(6) NULL,
  `CREATED_AT` TIMESTAMP(6) NULL,
  `CREATED_BY` VARCHAR(15) NULL,
  `UPDATED_AT` TIMESTAMP(6) NULL,
  `UPDATED_BY` VARCHAR(15) NULL,
  PRIMARY KEY (`GUID`));
